databases:
  - name: personal_blog
    databaseName: personal_blog
    user: personal_blog

services:
  - type: web
    name: personal_blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn personal_blog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal_blog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4